apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: iot-monitoring-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: temperature_db
