# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ask.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'ask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\task.proto\x12\x03\x61sk\"\x1e\n\nAskRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"\x1d\n\x0b\x41skResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2>\n\nAskService\x12\x30\n\x0b\x41skQuestion\x12\x0f.ask.AskRequest\x1a\x10.ask.AskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASKREQUEST']._serialized_start=18
  _globals['_ASKREQUEST']._serialized_end=48
  _globals['_ASKRESPONSE']._serialized_start=50
  _globals['_ASKRESPONSE']._serialized_end=79
  _globals['_ASKSERVICE']._serialized_start=81
  _globals['_ASKSERVICE']._serialized_end=143
# @@protoc_insertion_point(module_scope)
