# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperature.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'temperature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperature.proto\x12\x0btemperature\"\x07\n\x05\x45mpty\"/\n\x0bTemperature\x12\r\n\x05value\x18\x01 \x01(\x02\x12\x11\n\ttimestamp\x18\x02 \x01(\t2\xa0\x01\n\x12TemperatureService\x12\x45\n\x15GetCurrentTemperature\x12\x12.temperature.Empty\x1a\x18.temperature.Temperature\x12\x43\n\x11StreamTemperature\x12\x12.temperature.Empty\x1a\x18.temperature.Temperature0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_TEMPERATURE']._serialized_start=43
  _globals['_TEMPERATURE']._serialized_end=90
  _globals['_TEMPERATURESERVICE']._serialized_start=93
  _globals['_TEMPERATURESERVICE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
